site_name: Starlite Barebones Template
repo_url: https://github.com/JacobCoffee/starlite-barebones-template
edit_uri: ./edit/main/docs
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  version:
    provider: mike
plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - Usage Guide:
      - Installation: usage_guide/installation.md
      - Setup: usage_guide/developer_setup.md
      - Workflows: usage_guide/workflows.md
      - Releases: usage_guide/releases.md
